BEGIN;
CREATE TABLE "c3_productos" (gid serial PRIMARY KEY,id_serv int8,productos varchar(100));
insert into "c3_productos"(id_serv,productos) values (1,'credito hipotecario');
insert into "c3_productos"(id_serv,productos) values (2,'rentafija');
insert into "c3_productos"(id_serv,productos) values (3,'tarjeta credito');
insert into "c3_productos"(id_serv,productos) values (4,'tarjeta debito');
insert into "c3_productos"(id_serv,productos) values (5,'credito libre inversion');
insert into "c3_productos"(id_serv,productos) values (6,'credito vehiculo');
insert into "c3_productos"(id_serv,productos) values (7,'cdts');
insert into "c3_productos"(id_serv,productos) values (8,'compra cartera');
insert into "c3_productos"(id_serv,productos) values (9,'visa');
insert into "c3_productos"(id_serv,productos) values (10,'mastercard');
insert into "c3_productos"(id_serv,productos) values (11,'transferencias');
insert into "c3_productos"(id_serv,productos) values (12,'consignaciones');
insert into "c3_productos"(id_serv,productos) values (13,'horario extendido');
insert into "c3_productos"(id_serv,productos) values (14,'creditos por libranza');
insert into "c3_productos"(id_serv,productos) values (15,'hipoteca');
insert into "c3_productos"(id_serv,productos) values (16,'tasa fija');
insert into "c3_productos"(id_serv,productos) values (17,'inversiones en dolares');
insert into "c3_productos"(id_serv,productos) values (18,'corredores de bolsa');
END;
